//
//  toyboxes.h - include file auto-generated by toybox.py (https://toyboxpy.io).
//

#include "github.com/DidierMalenfant/pdbase/pdbase/pdbase.h"
#include "github.com/DidierMalenfant/playbox2d/playbox2d/playbox2d.h"

#define REGISTER_TOYBOXES(pd)   register_pdbase(pd); \
                                register_playbox2d(pd);
